name: Setup - tool

inputs:
  jdk_distribution:
    type: string
    required: false
    default: 'corretto'

runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.jdk_distribution }}
        java-version: 21

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Install Go Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x

