name: Checkout dependent subproject

inputs:
  checkout_token:
    required: true
    description: 'Github repo checkout token'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        repository: 'PostVisioning/com.belthead.worker'
        path: project
        token: ${{ inputs.checkout_token }}

    - uses: actions/checkout@v4
      with:
        repository: 'PostVisioning/com.belthead.core.general'
        path: project/subproject/belthead.core.general
        token: ${{ inputs.checkout_token }}

    - uses: actions/checkout@v4
      with:
        repository: 'PostVisioning/com.belthead.core.external'
        path: project/subproject/belthead.core.external
        token: ${{ inputs.checkout_token }}

    - uses: actions/checkout@v4
      with:
        repository: 'PostVisioning/com.belthead.runner'
        path: project/subproject/belthead.runner
        token: ${{ inputs.checkout_token }}
