name: Verification - native
on:
  workflow_call:
    inputs:
      local_deployment_package_artifact_name:
        type: string
      prod_deployment_package_artifact_name:
        type: string
      local_project_bundle_artifact_name:
        type: string
      prod_project_bundle_artifact_name:
        type: string
  workflow_dispatch:
    inputs:
      local_deployment_package_artifact_name:
        type: string
      prod_deployment_package_artifact_name:
        type: string
      local_project_bundle_artifact_name:
        type: string
      prod_project_bundle_artifact_name:
        type: string
jobs:
  build-native-local:
    uses: ./.github/workflows/build-native.yml
    secrets: inherit
    with:
      spring_profiles_active: 'local-native'
      deployment_package_artifact_name: ${{ inputs.local_deployment_package_artifact_name != ''&& inputs.local_deployment_package_artifact_name || 'local-deployment-package-native' }}
      project_bundle_artifact_name: ${{ inputs.local_project_bundle_artifact_name != ''&& inputs.local_project_bundle_artifact_name || 'local-project-bundle-native' }}

  build-native-prod:
    uses: ./.github/workflows/build-native.yml
    secrets: inherit
    with:
      spring_profiles_active: 'prod'
      deployment_package_artifact_name: ${{ inputs.prod_deployment_package_artifact_name != ''&& inputs.prod_deployment_package_artifact_name || 'prod-deployment-package-native' }}
      project_bundle_artifact_name: ${{ inputs.prod_project_bundle_artifact_name != ''&& inputs.prod_project_bundle_artifact_name || 'prod-project-bundle-native' }}
