name: Verification - native
on:
  repository_dispatch:
    types: [ verification--com-beltehad-worker ]
  workflow_call:
    inputs:
      project_ref:
        type: string
        default: dev
  workflow_dispatch:
    inputs:
      project_ref:
        type: string
        default: dev

permissions:
  actions: write

jobs:
  triggerVerification:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: '${{ github.repository_owner }}',
              repo: '${{ github.event.repository.name }}',
              workflow_id: 'verification-arm64-ubuntu22.yml',
              ref: '${{ github.ref }}',
              inputs: {"project_ref": "${{ inputs.project_ref }}"}
            })
            console.log(result);
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: '${{ github.repository_owner }}',
              repo: '${{ github.event.repository.name }}',
              workflow_id: 'verification-x64-ubuntu22.yml',
              ref: '${{ github.ref }}',
              inputs: {"project_ref": "${{ inputs.project_ref }}"}
            })
            console.log(result);
